### ISSUE TITLE
随便点了几下在线的示例，栈溢出

### ISSUE THREAD

**Issue by zhuweiyou** [OrangeXC/n2ex#23]
https://n2ex-gygymkmkgw.now.sh/topic/400256

```
Nuxt.js Error:

RangeError: Maximum call stack size exceeded
    at VueComponent.Component.options.data (server-bundle.js:469:37)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
    at VueComponent.Component.options.data (server-bundle.js:470:30)
```

**Comment by OrangeXC** [comment]
当时写项目的时候是

```
"nuxt": "^1.0.0-alpha.4"
```  

我找到了这个 issue: https://github.com/nuxt/nuxt.js/issues/1354

issue 结尾 `pi0` 说

> Problem should be finally fixed with rc8 🎉

随着框架的升级问题已经被解决，但是仍然处于不稳定版本。

等到 nuxt 主版本 release 到 1.0.0 之后，我会重构一次这个项目，感谢提 issue
